# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /#about
    weight: 15
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Publications
    url: /#papers
    weight: 40
  - name: Travel
    url: travel/
    weight: 50
  - name: Blog
    url: /#news
    weight: 60
