# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: cyan

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Wang Likun'
    description: 'Personal website of Wang Likun, Algorithm Engineer specializing in TPU operator development, deep learning, and biomechanical topology optimization. M.Eng. from Waseda University.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "ðŸš€ Wang Likun"

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Wang Likun | Algorithm Engineer'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  comment:
    provider: ''
